### ISSUE TITLE
The bot no longer works

### ISSUE THREAD

**Issue by SziluChannel** [theincompleteguide/incomplete-trading-bot#7]
The alpaca API that is used in this is deprecated.

**Comment by ctoxyz** [comment]
gives lots of errors - 

Traceback (most recent call last):
  File "D:\_git\incomplete-trading-bot\tbot.py", line 8, in <module>
    from traderlib import *
  File "D:\_git\incomplete-trading-bot\traderlib.py", line 7, in <module>
    import alpaca_trade_api as tradeapi
  File "D:\_git\incomplete-trading-bot\alpaca_trade_api\__init__.py", line 1, in <module>
    from .rest import REST  # noqa
  File "D:\_git\incomplete-trading-bot\alpaca_trade_api\rest.py", line 12, in <module>
    from .entity import (
  File "D:\_git\incomplete-trading-bot\alpaca_trade_api\entity.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
